### ISSUE TITLE
aes_cbc_enc crashing if unrelated class is instantiated

### ISSUE THREAD

**Issue by jondea** [DavyLandman/AESLib#10]
First of all, thanks for this great library and apologies if this bug is entirely my doing. I am getting some odd crashing in a sketch of mine, and after several days of searching I whittled it down to this. The normal ECB AES128 works fine all the time (as far as I can tell), but CBC sometimes crashes. The only cause I can find is instantiating the class EthernetClient (from [UIPEthernet.h](https://github.com/ntruchsess/arduino_uip)). It may be the case that it's the fault of that library, but it crashes when the aes128_cbc_enc (or aes192_cbc_enc) function is called.

Sketch I used:

``` c++
#include <Arduino.h>
#include <AESLib.h>
#include <UIPEthernet.h>

const uint8_t key[16] = {'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a'};
//const uint8_t key[24] = {'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a'};
//const uint8_t key[32] = {'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a','a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a'};


// Comment this out and it works
EthernetClient client;

void setup() {

  Serial.begin(9600);

  Serial.println("Starting EBC test");
  uint8_t key[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
  char data[] = "0123456789012345"; //16 chars == 16 bytes
  aes128_enc_single(key, data);
  Serial.print("encrypted:");
  Serial.println(data);
  aes128_dec_single(key, data);
  Serial.print("decrypted:");
  Serial.println(data);
  Serial.println("Finished EBC test without seg fault");
  delay(100);

  cbcTest();
}

void loop() {}

void cbcTest() {

  Serial.println("Entered cbcTest()");

  //char data[] = "0123456789012345"; //16 chars == 16 bytes

  uint16_t dataLength = 96;
  char data[] = "abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop";

  uint16_t keyLength = 16;
  uint8_t iv[16] = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P'};
  //uint8_t iv[24] = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P','Q','R','S','T','U','V','W','X'};
  //uint8_t iv[32] = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P','A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P'};

  Serial.print("Plaintext: "); Serial.write(data, dataLength); Serial.println("");
  Serial.print("key: ");  Serial.write(key, keyLength); Serial.println("");
  Serial.print("IV: "); Serial.write(iv, keyLength);  Serial.println("");
  delay(1000);

  aes128_cbc_enc(key, iv, data, dataLength);

  Serial.print("Ciphertext: ");  Serial.write(data, dataLength);  Serial.println("");
  delay(100);

  Serial.println("Finished cbcTest() without seg fault");
  delay(100);
}
```

Here's the output from my included code:

```
Starting EBC test
encrypted:%ì›]˜?÷ßE¤¨žiü
decrypted:0123456789012345
Finished EBC test without seg fault
Entered cbcTest()
Plaintext: abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop
key: aaaaaaaaaaaaaaaa
IV: ABCDEFGHIJKLMNOP
Ciphertext: <lots of non-ASCII friendly characters>
Finished cbcTest() without seg fault
```

If you think this is a stupid question, or that the error is most likely in the other library could you tell me how you debug libraries such as your own (or even UIPEthernet.h)? The usual trick of using Serial.print is unsuitable for c libraries (I think).

**Comment by DavyLandman** [comment]
no idea, I'm sorry. perhaps ask on the other library's forum?

in general a segfault could be caused by a wrong pointer.. but not sure where it goes wrong on first sight.

**Comment by jondea** [comment]
Thanks for your reply.
Sure I will do, does it look likely it is the other library?

How do you go about debugging your library? Or more specifically, where would you start debugging such a problem?

**Comment by g-crash** [comment]
@jondea It looks like a problem i've encountered as well, i fixed it by optimizing memory, you could ytry to run your cbcTest() function at the start of setup instead of the end and ECB encryption up in an other function.

**Comment by astrosteve0** [comment]
This is definitely a problem for me, on an Arduino Mega. I can make a tiny example, and the cbc example works. However, with all my code, it fails in the encrypt call. Like most examples of something is overwriting the wrong memory, small changes can get it to work or fail. Since I'm the third person with this same issue, I'm going to say the common thread is this library, and not another library.  The best I can tell so far, the aes128_cbc_enc() function calls bcal_cbc_init(), which calls bcal_cipher_init() which calls init_fpt.init2((void*)key, keysize_b, (ctx->ctx)); from the file bcal-basic.c on line 50. I am unsure where the function is that it is calling there, since it it doing something I'm unfamiliar with. Thus I'm unable to trace it further (if I'm even on the right track). I need to learn more about debugging a library, and figure out where the function is that is being called there on line 50. Any ideas? I'd love for this to work, I need to encrypt data between the Arduino and a computer running a .Net program in C#.
