### ISSUE TITLE
missing 'recipe.S.o.pattern' configuration parameter

### ISSUE THREAD

**Issue by Villa2016** [DavyLandman/AESLib#11]
Thank you for this library, very useful and much more simple to use than others! However I have had one issue when compiling on Arduino IDE, I have used your example below;

Serial.begin(57600);
uint8_t key[] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15};
char data[] = "0123456789012345"; //16 chars == 16 bytes
aes128_enc_single(key, data);
Serial.print("encrypted:");
Serial.println(data);
aes128_dec_single(key, data);
Serial.print("decrypted:");
Serial.println(data);

And I am getting the error "missing 'recipe.S.o.pattern' configuration parameter" when trying to compile. Have you seen this issue before or know a fix for it? 

Kind Regards!

**Comment by DavyLandman** [comment]
nope, that's a new one, perhaps try on stackoverflow or a general arduino forum?

**Comment by JacksonLv** [comment]
I also met this problem when I chose other board to compile.My friend said it may because of the gcc rule but I am not sure about that.

**Comment by DavyLandman** [comment]
perhaps it is one of the newer boards with a different instruction set?
