### ISSUE TITLE
How to use the multiblock encryption/decyption?

### ISSUE THREAD

**Issue by joshuakaleb0424** [DavyLandman/AESLib#14]
The example given was only using the single one. Your help is much appreciated!

**Comment by kSuccess** [comment]
i have the same issue can you help ?

**Comment by panzer7910** [comment]
I have the same issue too. Sent email request to Davy Landman, probably he will spare some time in the documentation.

**Comment by DavyLandman** [comment]
I'm very busy, no time for a long answer.

I'll just point out three options on how to answer this question:
1. Use the force, read the source! https://github.com/DavyLandman/AESLib/blob/master/AESLib.h
2. Look for how other github projects are using the code: https://github.com/search?q=aes128_cbc_enc_start&type=Code
3. Turn it into a StackOverflow question.

**Comment by AvelinoMorganti** [comment]
I have the same issue can you help?
