### ISSUE TITLE
Strange response

### ISSUE THREAD

**Issue by ZeratlulSC** [DavyLandman/AESLib#16]
Hello
I used to your project to encrypt messadge "EEEEEEEEEEEEEEEE" : result was "xi6v	"
Shouldn't this algoright return 16 bytes of encrypted data?
Thanks

**Comment by ZeratlulSC** [comment]
It was correct.

**Comment by DavyLandman** [comment]
I think you were printing the bytes as a string, but it contained a '\0' so it stopped printing.

Next time, print the bytes as hexagonal values?
