### ISSUE TITLE
Ciphering doesn't match with others generated with Java or Nodejs

### ISSUE THREAD

**Issue by rsegecin** [DavyLandman/AESLib#17]
The same bytes encrypted using AESLib with the same key, initialization vector and encryption mode have a different output than Java or Nodejs.  Follows the example code:

	#include <AESLib.h>

	const PROGMEM char HEX_VALUES[] = { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F' };

	#define CBLOCK (1 * N_BLOCK) + 1

	char serialBuffer[120];

	void setup() {
		Serial.begin(115200);
	}

	void loop() {
		crypt();
		delay(10000);
	}

	void ByteToHexString(char * hexStrParam, unsigned char * byteArrayParam, unsigned int byteArrayLength)
	{
		unsigned char num;

		for (int i = 0, u = 0; i < byteArrayLength; i++, u++)
		{
			num = byteArrayParam[i] >> 4;
			hexStrParam[u] = (char)pgm_read_byte(HEX_VALUES + num);
			num = byteArrayParam[i] & 0xf;
			hexStrParam[++u] = (char)pgm_read_byte(HEX_VALUES + num);
		}
	}

	void crypt() {
		uint8_t key[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 };
		uint8_t iv[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 };
		char data[16];
		aes_context ctx;
		char auxBuffer[129];

		memset(data, 0x00, 16);
		memcpy(data, "rinaldi", 7);

		ctx = aes128_cbc_enc_start((const uint8_t*)key, iv);
		aes128_cbc_enc_continue(ctx, data, 16);
		aes128_cbc_enc_finish(ctx);

		memset(auxBuffer, 0x00, 129);
		ByteToHexString(auxBuffer, (unsigned char *)data, sizeof(data));
		sprintf(serialBuffer, "encrypted-cbc: %s", auxBuffer);
		Serial.println(serialBuffer);

		ctx = aes128_cbc_dec_start((const uint8_t*)key, iv);
		aes128_cbc_dec_continue(ctx, data, 16);
		aes128_cbc_dec_finish(ctx);

		sprintf(serialBuffer, "decrypted-cbc: %s", data);
		Serial.println(serialBuffer);

		memset(auxBuffer, 0x00, 129);
		ByteToHexString(auxBuffer, (unsigned char *)iv, sizeof(iv));
		sprintf(serialBuffer, "iv: %s", auxBuffer);
		Serial.println(serialBuffer);
	}

Output:

 	encrypted-cbc: 2FD27523B3E1B5A122F397A5F976A680
	decrypted-cbc: rinaldi
	iv: 000102030405060708090A0B0C0D0E0F

This lines can be run with Nodejs:

	var crypto = require("crypto");
	var key = new Buffer([ 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 ]);
	var iv = new Buffer([ 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 ]);
	var cipher = crypto.createCipheriv("aes-128-cbc", key, iv);
	var crypted = Buffer.concat([cipher.update(Buffer.from("rinaldi")), cipher.final()]);
	var encryptedHex = crypted.toString('hex')
		encryptedHex

Or execute this method with Java:

	public static String encrypt() {
		try {
			byte key[] = new byte[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 };
			byte iv[] = new byte[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 };

			SecretKeySpec skeySpec = new SecretKeySpec(key, "AES");

			Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5PADDING");
			cipher.init(Cipher.ENCRYPT_MODE, skeySpec, new IvParameterSpec(iv));

			byte[] encrypted = cipher.doFinal("rinaldi".getBytes());

			return Utils.HexString(encrypted);
		} catch (Exception ex) {
			ex.printStackTrace();
		}
		return null;
	}

The output from both Nodejs and Java give me: `58346027133deead261e621b676f1bf6`

**Comment by DavyLandman** [comment]
Aren't you comparing different padding modes? In the C example you are
padding with zero. What's node and Java doing?

**Comment by rsegecin** [comment]
Yes @DavyLandman you're right. Java and Nodejs are doing padding with PKCS#5. I couldn't find NoPadding with these languages so I'm writing PKCS#5 pad function to run with your library instead. Apparently there are no forks with this feature already. Have you considered adding it? you can close this issue if you wanted.

**Comment by DavyLandman** [comment]
I haven't worked on this library for a long time, if you want to add a PKCS#5 padding implementation: go right ahead :) I'll happily merge a pull request.

But in a way, that's all before the actual encryption function runs. So in a way you could write that separately from this library.

**Comment by DavyLandman** [comment]
Ow, and with both java and node, there must be a way to pass a 16 byte array with zeros in the same way as you did for the C version.

Closing it for now.

**Comment by rsegecin** [comment]
I'll see what I do. Thank you very much @DavyLandman.

**Comment by Henry586** [comment]
try to set nopadding parameter:

JS:
    var encrypted =  CryptoJS.AES.encrypt(message, key, {'iv': iv,'padding': CryptoJS.pad.NoPadding, 'mode': CryptoJS.mode.CBC});


Java:
			Cipher cipher = Cipher.getInstance("AES/CBC/NoPadding");
