### ISSUE TITLE
Arduino Not Compiling with the Library 

### ISSUE THREAD

**Issue by VinodAmarathunga** [DavyLandman/AESLib#24]
Hi, 

I was trying the AES libaray for one of my projects, 

But when adding libabry and running the example code I am getting below error in IDE 
![Capture](https://user-images.githubusercontent.com/62054067/76399883-6a284880-63a5-11ea-9d92-465d0d621205.JPG)

**Comment by woytam** [comment]
Hard to guess, but are sure, you have function loop() in your project?
