### ISSUE TITLE
save against replay attack

### ISSUE THREAD

**Issue by halukmy** [DavyLandman/AESLib#25]
how can we use it on lora replay attack?

**Comment by MihaMarkic** [comment]
I guess you could include a current date value and check for the allowed span.

**Comment by halukmy** [comment]
@MihaMarkic thanks for message, can you share simple sample? i fony hry iy

**Comment by MihaMarkic** [comment]
@halukmy Here is the idea. As a part of your content, include current date. When you decrypt the content on the other side, check if currentdate-date_from_content < ALLOWED_SPAN

**Comment by DavyLandman** [comment]
Better switch to a AEAD construct, like for example [ChaCha20-Poly1305](https://github.com/DavyLandman/portable8439) where you can include some data that changes for every request.

**Comment by halukmy** [comment]
dear @DavyLandman we follow it on esp or server? can you share some lines of code?

**Comment by DavyLandman** [comment]
The chacha20-pooy1305 has direct support in most programming languages.

The library works on esp8266, and server side you can pick any language you'll like and encrypt&decrypt data.
