### ISSUE TITLE
Cant Compile: Missing avr/io.h

### ISSUE THREAD

**Issue by bellspen** [DavyLandman/AESLib#26]
I've tried adding the include of avr/io.h. But I get a compiler error with that too saying it cant find avr/io.h.

Compiler Output:
In file included from D:\Program Files (x86)\Arduino\libraries\AESLib\aes_dec-asm_faster.S:28:0:

D:\Program Files (x86)\Arduino\libraries\AESLib\avr-asm-macros.S:31:20: fatal error: avr/io.h: No such file or directory

 #include <avr/io.h>

                    ^

compilation terminated.

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by simortus** [comment]
did you try with 
 #include "Arduino.h"
??

**Comment by DavyLandman** [comment]
Esp8266 is not avr instruction set.

Also, esp8266-arduino already contains aes encryption library.
