### ISSUE TITLE
Example Simple doesn't really work

### ISSUE THREAD

**Issue by JaBa1202** [DavyLandman/AESLib#32]
Running the example will ALWAYS report success but it is a false success report. Even if you change the line decLen = decrypt(...) to decLen = 0, it will report a successful decrypt though it didn't even decrypt it. Actually, I don't think it could ever work. The library indicates that encrypt and decrypt DO NOT use Base64 encoding but the example "simple" does a base64 encode before calling decrypt.

**Comment by sudo0xn14r** [comment]
I am running into the same issue, and it seems like the function call to encrypt transforms the text somehow into Base64 on its own, i was not able to understand clearly, did find any resolutions? @JaBa1202

**Comment by DavyLandman** [comment]
Where is base64 mentioned? Which example are you talking about?

`decLen = decrypt` doesn't appear in the example (nor the API).

I'm closing this issue, I think you are reporting something to the wrong repo.

**Comment by JaBa1202** [comment]
> I am running into the same issue, and it seems like the function call to encrypt transforms the text somehow into Base64 on its own, i was not able to understand clearly, did find any resolutions? @JaBa1202



> Where is base64 mentioned? Which example are you talking about?
> 
> `decLen = decrypt` doesn't appear in the example (nor the API).
> 
> I'm closing this issue, I think you are reporting something to the wrong repo.

Davy, you are correct: wrong repo. This issue aüülies to AESLib by Matej Sychra. Sorry for the confusion.
