### ISSUE TITLE
Help: Cross-platform decryption issue 

### ISSUE THREAD

**Issue by nrempe** [DavyLandman/AESLib#6]
Hi Davy,

First, thanks for the fabulous AES library. It's very easy to use on the Arduino platform. Excellent work.

That said, I could use your help. I'm moving data encrypted by your library from the Arduino to a Windows 8.1 platform where I want to decrypt it using a c# application. As of this moment, I've been unsuccessful doing so.

The following snippets show the encryption and base64 encoding of the encrypted char array on the arduino, which is then transferred over serial to the application on the Windows machine, where the c# Decrypt function shown below is executed.

However, I get "The input data is not a complete block" errors in the c# application when trying to decrypt the data and after many hours of trying to work through a solution, I'm hoping you can point me in the right direction.

Can you help? Thanks so much.

Nate

```
// Arduino
#include <AESLib.h>
#include <Base64.h>

void setup()
{
 Serial.begin(9600);
}

void loop()
{ 
char data[17] = "1234123412341234";
const uint8_t key[] PROGMEM = {1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7};
aes128_enc_single(key, data);
char b64Data[base64_enc_len(sizeof(data))];
base64_encode(b64Data, data, sizeof(data));
}
```

```
// C#
        public static string Decrypt(string cipherText)
        {
            string EncryptionKey = "1234567891234567";
            byte[] cipherBytes = Convert.FromBase64String(cipherText);
            using (Aes encryptor = Aes.Create())
            {
                encryptor.Mode = CipherMode.CBC;
                encryptor.Padding = PaddingMode.None;
                Rfc2898DeriveBytes pdb = new
                    Rfc2898DeriveBytes(EncryptionKey, new byte[] { 0x49, 0x76, 0x61, 0x6e, 0x20, 0x4d, 0x65, 0x64, 0x76, 0x65, 0x64, 0x65, 0x76 });
                encryptor.Key = pdb.GetBytes(32);
                encryptor.IV = pdb.GetBytes(16);
                using (MemoryStream ms = new MemoryStream())
                {
                    using (CryptoStream cs = new CryptoStream(ms, encryptor.CreateDecryptor(), CryptoStreamMode.Write))
                    {
                        cs.Write(cipherBytes, 0, cipherBytes.Length);
                        cs.Close();
                    }
                    cipherText = Encoding.Unicode.GetString(ms.ToArray()); 
                }
            }
            return cipherText;
        }
[END C# CODE SNIPPET]
```

**Comment by DavyLandman** [comment]
This tends to be a problem of syncing your c and c# code to do exactly the same.

**Comment by DavyLandman** [comment]
so for example:

```
   Rfc2898DeriveBytes pdb = new
                    Rfc2898DeriveBytes(EncryptionKey, new byte[] { 0x49, 0x76, 0x61, 0x6e, 0x20, 0x4d, 0x65, 0x64, 0x76, 0x65, 0x64, 0x65, 0x76 });
    
```

is different.

**Comment by nrempe** [comment]
Thanks. Got it figured out...

Sent from my iPhone 6

On Jan 25, 2015, at 9:37 AM, Davy Landman <notifications@github.com> wrote:

so for example:

   Rfc2898DeriveBytes pdb = new
                    Rfc2898DeriveBytes(EncryptionKey, new byte[] { 0x49, 0x76, 0x61, 0x6e, 0x20, 0x4d, 0x65, 0x64, 0x76, 0x65, 0x64, 0x65, 0x76 });

is different.

**Comment by Namures** [comment]
> Thanks. Got it figured out...

Excuse me, sorry if this's an old issue. I'm curious how's the solution. I have the same problem. Thanks.
