### ISSUE TITLE
ESP Compatible?

### ISSUE THREAD

**Issue by ripper121** [DavyLandman/AESLib#7]
I tested your Lib with the ESP8266 but it dont complie.
Is the a way to implement it without ASM?

**Comment by NateZimmer** [comment]
Heh... same problem

**Comment by JohnAntonusMaximus** [comment]
Bueller? +1

**Comment by pjunni** [comment]
I get lines like:
.piolibdeps/AESLib/avr-asm-macros.S:31:20: fatal error: avr/io.h: No such file or directory
what should be done?

**Comment by NateZimmer** [comment]
I ended up using: https://github.com/kokke/tiny-AES-c .

**Comment by DavyLandman** [comment]
Nope, not esp compatible, but arduino-esp8266 has BearSSL buildin, that already contains an aes implementation (and also chacha20)
